wandb_version: 1

hidden:
  desc: null
  value: 120
seed:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 50
knn:
  desc: null
  value: 6
K:
  desc: null
  value: 7
mlp:
  desc: null
  value: 4
window_size:
  desc: null
  value: 2
num_layers:
  desc: null
  value: 4
lr:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 10
train:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1741952317.700431
    t:
      1:
      - 1
      - 5
      - 49
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 49
      - 53
      - 55
      - 77
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.2
      8:
      - 5
