run_mode: grid_search
parameters:
  batch_size: 64
  num_epochs: 10
  learning_rate: 1e-5
  num_gen: 5000
  save_interval: 50
  model_type: "mlp_v2"
  beta_start: 5e-6
  beta_end: 0.03
  diffusion_steps: 1400
  num_instances: 3
  h5_file_path: "latent_reps/sidechain_pooled.h5"
  dataset_key: "sidechain_pooled"
  output_dir: "latent_reps/diff_sidechain"
  pooling_dim: [20,3]
