use_debug_logs: true
log_file: logfile4.log

json_path: ../../my_protein.json
pdb_filename: ../heavy_chain.pdb
knn_value: 4
cheb_order: 4
hidden_dim: 4

output_directories:
  checkpoint_dir: checkpoints
  structure_dir: structures
  latent_dir: latent_reps

hno_training:
  batch_size: 16
  learning_rate: 0.0001
  num_epochs: 1200
  save_interval: 1

decoderB_training:
  batch_size: 16
  learning_rate: 0.0001
  num_epochs: 1500
  save_interval: 1
  decoder_depth: 4

decoderSC_training:
  batch_size: 16
  learning_rate: 0.0001
  num_epochs: 1500
  save_interval: 1
  decoder_depth: 8
  arch_type: 0  # or 1 or 2

pooling_dim_backbone: [40,1]
pooling_dim_sidechain: [20,3]

# pooling_dim_backbone: [30,1]
# pooling_dim_sidechain: [10,3]

hno_ckpt: hno_model.pth
